### ISSUE TITLE
trainer.validate returns different values each time it is called

### ISSUE THREAD

**Issue by helpmyRF24isntworking** [MathiasKraus/neural_network_course_WS2425#2]
trainer.validate(model, data_module.val_dataloader())
<img width="500" alt="image" src="https://github.com/user-attachments/assets/d30a7326-c876-41c2-922b-3cc2a7e165c6">

<img width="559" alt="image" src="https://github.com/user-attachments/assets/9e52ba4f-f52a-4216-aa0d-d18e01d8c48d">

**Comment by MathiasKraus** [comment]
Thanks for raising this point. As discussed in the exercise, we need to set the random seed in order to get the same train/val/test split each time.
